```{r setup,echo=FALSE}
library(knitr)
opts_chunk$set(
  fig.path=paste0(fig.path, "/"), 
  fig.align='left', 
  comment="",
  echo=FALSE, 
  warning=FALSE, 
  error=TRUE, 
  message=FALSE, 
  cache=FALSE, 
  dpi=100,
  ##dev=c("svg", "png", "pdf", "postscript"),
  dev="svg",
  results="asis")
options(knitr.table.format = 'html')
```

# `r basename(cur_dir)` attrition table
`r format(Sys.Date(), "%b %d %Y")`

```{r stats, fig.width=8, fig.height=10, results='asis'}
null <- sapply(seq(plotList), function(i) {
    breaks = 10**(1:10)
    
    p <- ggplot(plyr::rbind.fill(stats.mdf.listBygtsp[ plotList[[i]] ]), 
                aes(variable, value, fill=Replicate)) +
        geom_bar(position=position_dodge(width = 0.8), stat="identity") + 
        ##scale_y_log10() +
        scale_y_log10(breaks = breaks, labels = comma(breaks)) +
        ##coord_flip() +
        theme_default +
        facet_wrap( ~ gtspinfo, ncol=1, scales = "free_y")
    print(p)
    cat("<hr>", "\n")
    cat("<P style=\"page-break-before: always\">", "\n")
} )
```

